const GREET_CODE = 101;
const NEWPLAYER_CODE = 102;
const MOVE_CODE = 103
const ROOMLIST_CODE = 104;
const FETCHRULE_CODE = 105;
const SELECTEDRULE_CODE = 106;

module.exports = {
	GREET_CODE:GREET_CODE,
	NEWPLAYER_CODE:NEWPLAYER_CODE,
	MOVE_CODE:MOVE_CODE,
	ROOMLIST_CODE:ROOMLIST_CODE,
    SELECTEDRULE_CODE= SELECTEDRULE_CODE,
    FETCHRULE_CODE: FETCHRULE_CODE, 
}
