const GREET_CODE = 101;
const NEWPLAYER_CODE = 102;
const MOVE_CODE = 103
const ROOMLIST_CODE = 104;
const FETCHRULE_CODE = 105;
const LOBBYDETAILS_CODE = 106;
const JOINGAME_CODE = 107;
const CARD_CODE = 108;
const READY_CODE = 110;
const STARTGAME_CODE = 111;
const DEALCARD_CODE = 112;
const REQUESTAVATARS_CODE = 113;
const GAMEROOM_OCCUPIED = 50;
const ENDDISTRIBUTE = 49;

const TURN_CODE = 53;
const STATE_CODE = 51;
const PASSTURN_CODE = 54;
const INVALIDMOVE_CODE = 55;
const DELETEDEALT_CODE = 56;
const ROUNDWIN_CODE = 57;
const NEWROUND_CODE = 58;
const RULES_LIST = 59;
const BOTRULES_LIST = 60;
const MESSAGESEQ_CODE = 61;

module.exports = {
    MESSAGESEQ_CODE: MESSAGESEQ_CODE,
    BOTRULES_LIST:BOTRULES_LIST,
    CARD_CODE:CARD_CODE,
	GREET_CODE:GREET_CODE,
	NEWPLAYER_CODE:NEWPLAYER_CODE,
	MOVE_CODE:MOVE_CODE,
	ROOMLIST_CODE:ROOMLIST_CODE,
    LOBBYDETAILS_CODE: LOBBYDETAILS_CODE,
    FETCHRULE_CODE: FETCHRULE_CODE, 
    JOINGAME_CODE:JOINGAME_CODE,
    GAMEROOM_OCCUPIED: GAMEROOM_OCCUPIED,
    READY_CODE:READY_CODE,
    DEALCARD_CODE:DEALCARD_CODE,
    ENDDISTRIBUTE:ENDDISTRIBUTE,
    STARTGAME_CODE:STARTGAME_CODE,
    STATE_CODE:STATE_CODE,
    TURN_CODE:TURN_CODE,
    PASSTURN_CODE:PASSTURN_CODE,
    INVALIDMOVE_CODE:INVALIDMOVE_CODE,
    DELETEDEALT_CODE:DELETEDEALT_CODE,
    ROUNDWIN_CODE:ROUNDWIN_CODE,
    NEWROUND_CODE:NEWROUND_CODE,
    RULES_LIST:RULES_LIST,
    REQUESTAVATARS_CODE:REQUESTAVATARS_CODE
}
