const GREET_CODE = 101;
const NEWPLAYER_CODE = 102;
const MOVE_CODE = 103
const ROOMLIST_CODE = 104;
const FETCHRULE_CODE = 105;
const LOBBYDETAILS_CODE = 106;
const JOINGAME_CODE = 107;
const CARD_CODE = 108;
const READY_CODE = 110;
const STARTGAME_CODE = 111;
const DEALCARD_CODE = 112;
const GAMEROOM_OCCUPIED = 50;
const ENDDISTRIBUTE = 49;

const TURN_CODE = 53;
const STATE_CODE = 51;
const PASSTURN_CODE = 54;
const INVALIDMOVE_CODE = 55;

module.exports = {
    CARD_CODE:CARD_CODE,
	GREET_CODE:GREET_CODE,
	NEWPLAYER_CODE:NEWPLAYER_CODE,
	MOVE_CODE:MOVE_CODE,
	ROOMLIST_CODE:ROOMLIST_CODE,
    LOBBYDETAILS_CODE: LOBBYDETAILS_CODE,
    FETCHRULE_CODE: FETCHRULE_CODE, 
    JOINGAME_CODE:JOINGAME_CODE,
    GAMEROOM_OCCUPIED: GAMEROOM_OCCUPIED,
    READY_CODE:READY_CODE,
    DEALCARD_CODE:DEALCARD_CODE,
    ENDDISTRIBUTE:ENDDISTRIBUTE,
    STARTGAME_CODE:STARTGAME_CODE,
    STATE_CODE:STATE_CODE,
    TURN_CODE:TURN_CODE,
    PASSTURN_CODE:PASSTURN_CODE,
    INVALIDMOVE_CODE:INVALIDMOVE_CODE
}
