const GREET_CODE = 101;
const LOBBYDETAILS_CODE = 106;
const JOINGAME_CODE = 107;
const CARD_CODE = 108;
const REQUESTAVATARS_CODE = 113;

const TURN_CODE = 53;

module.exports = {
	TURN_CODE:TURN_CODE,
	CARD_CODE:CARD_CODE,
	GREET_CODE:GREET_CODE,
	LOBBYDETAILS_CODE:LOBBYDETAILS_CODE,
	JOINGAME_CODE:JOINGAME_CODE,
    REQUESTAVATARS_CODE:REQUESTAVATARS_CODE
}
