const GREET_CODE = 101;
const MOVE_CODE = 103;
const LOBBYDETAILS_CODE = 106;
const JOINGAME_CODE = 107;
const CARD_CODE = 108;
const REQUESTAVATARS_CODE = 113;

const TURN_CODE = 53;
const PASSTURN_CODE = 54;
const DELETEDEALT_CODE = 56;
const ROUNDWIN_CODE = 57;
const NEWROUND_CODE = 58;
const RULES_LIST = 59;
const BOTRULES_LIST = 60;
const MESSAGESEQ_CODE = 61;

module.exports = {
	ROUNDWIN_CODE:ROUNDWIN_CODE,
	DELETEDEALT_CODE:DELETEDEALT_CODE,
	MESSAGESEQ_CODE:MESSAGESEQ_CODE,
	NEWROUND_CODE:NEWROUND_CODE,
	RULES_LIST:RULES_LIST,
	BOTRULES_LIST:BOTRULES_LIST,
	PASSTURN_CODE:PASSTURN_CODE,
	MOVE_CODE:MOVE_CODE,
	TURN_CODE:TURN_CODE,
	CARD_CODE:CARD_CODE,
	GREET_CODE:GREET_CODE,
	LOBBYDETAILS_CODE:LOBBYDETAILS_CODE,
	JOINGAME_CODE:JOINGAME_CODE,
    REQUESTAVATARS_CODE:REQUESTAVATARS_CODE
}
